import * as path from "node:path";

import type { DatabaseAdapter } from "@mooncg/database-adapter-types";
import * as Sentry from "@sentry/node";
import { Effect, PubSub } from "effect";
import express from "express";
import semver from "semver";

import { stringifyError } from "../../shared/utils/errors.js";
import type { MoonCG } from "../../types/mooncg.js";
import type { RootNS } from "../../types/socket-protocol.js";
import { serverApiFactory } from "../api.server.js";
import { config, sentryEnabled } from "../config/index.js";
import { createLogger } from "../logger/index.js";
import type { Replicator } from "../replicant/replicator.js";
import { purgeModuleCache } from "../util/module-cache.js";
import { BundleEvent, type BundleService } from "./bundle-service.js";

const log = createLogger("extensions");

export interface ExtensionEventMap {
	login: (user: Express.Request["user"]) => void;
	logout: (user: Express.Request["user"]) => void;
	extensionsLoaded: () => void;
	serverStarted: () => void;
	serverStopping: () => void;
	/**
	 * Emitted (only to the affected API instance) right before the
	 * extension is unloaded during a hot-reload. Extensions must use this to
	 * clean up any resources they own (timers, sockets, DB handles, ...).
	 * Resources that are not cleaned up here will leak.
	 */
	bundleUnloading: () => void;
	/**
	 * Emitted to all API instances after a bundle's extension has been
	 * successfully hot-reloaded. Useful for dependents that want to react to
	 * the reload of a bundle they depend on.
	 */
	extensionReloaded: (bundleName: string) => void;
}

export const createExtensionManager = Effect.fn("createExtensionManager")(
	function* (
		io: RootNS,
		bundleService: BundleService,
		replicator: Replicator,
		mount: MoonCG.Middleware,
		db: DatabaseAdapter,
	) {
		const extensions: Record<string, unknown> = {};
		const apiInstances = new Set<
			InstanceType<ReturnType<typeof serverApiFactory>>
		>();
		const apiInstancesByBundle = new Map<
			string,
			InstanceType<ReturnType<typeof serverApiFactory>>
		>();

		/**
		 * All bundles whose extension is currently loaded, by bundle name.
		 * Used to compute the dependents cascade on hot-reload.
		 */
		const loadedBundles = new Map<string, MoonCG.Bundle>();

		/**
		 * The current per-bundle mount router. `mooncg.mount()` writes into
		 * this router instead of the main app, so that all routes of a bundle
		 * can be detached again by swapping (or removing) the router.
		 */
		const mountRouters = new Map<string, express.Router>();

		/**
		 * Bundles for which the stable delegation middleware has already been
		 * mounted into the main app. The delegator is mounted at most once per
		 * bundle and survives extension reloads; only the router it delegates
		 * to is swapped.
		 */
		const mountDelegators = new Set<string>();

		const satisfiedDepNames = new WeakMap<MoonCG.Bundle, string[]>();

		const createMount = (bundle: MoonCG.Bundle): MoonCG.Middleware => {
			const mountForBundle = (...args: any[]) => {
				let router = mountRouters.get(bundle.name);
				if (!router) {
					router = express.Router();
					mountRouters.set(bundle.name, router);
				}

				if (!mountDelegators.has(bundle.name)) {
					mountDelegators.add(bundle.name);
					mount(
						(
							req: express.Request,
							res: express.Response,
							next: express.NextFunction,
						) => {
							const currentRouter = mountRouters.get(bundle.name);
							if (currentRouter) {
								currentRouter(req, res, next);
							} else {
								next();
							}
						},
					);
				}

				return (router.use as (...useArgs: any[]) => unknown)(...args);
			};

			return mountForBundle as MoonCG.Middleware;
		};

		log.trace("Starting extension mounting");
		const ExtensionApi = serverApiFactory(
			io,
			replicator,
			extensions,
			createMount,
			db,
		);

		/**
		 * Requires and instantiates a bundle's extension. Throws when the
		 * extension code cannot be loaded; error handling is up to the caller
		 * (startup and hot-reload have different failure semantics).
		 */
		function mountExtension(bundle: MoonCG.Bundle): void {
			const extPath = path.join(bundle.dir, "extension");
			const requireFunc = process.env.MOONCG_TEST ? require : module.require;
			let mod = requireFunc(extPath);

			// If the extension has been generated by Babel/TypeScript and exported with "export default".
			if (mod.__esModule) {
				mod = mod.default;
			}

			// Give the bundle a fresh mount router. The stable delegation
			// middleware (mounted lazily on the first `mooncg.mount()` call)
			// always dispatches to the router that is current at request time.
			mountRouters.set(bundle.name, express.Router());

			const apiInstance = new ExtensionApi(bundle);
			apiInstances.add(apiInstance);
			apiInstancesByBundle.set(bundle.name, apiInstance);
			const extension = mod(apiInstance);
			log.info("Mounted %s extension", bundle.name);
			extensions[bundle.name] = extension;
			loadedBundles.set(bundle.name, bundle);
		}

		/**
		 * Unloads a bundle's extension: emits `bundleUnloading` to the
		 * affected API instance, tears the instance down, and removes the
		 * bundle's routes and extension reference. Replicants (and their
		 * state) are deliberately left untouched.
		 */
		function unloadExtension(bundle: MoonCG.Bundle): void {
			const apiInstance = apiInstancesByBundle.get(bundle.name);
			if (!apiInstance) {
				return;
			}

			apiInstance.emit("bundleUnloading");
			ExtensionApi.destroyApiInstance(apiInstance);
			apiInstances.delete(apiInstance);
			apiInstancesByBundle.delete(bundle.name);
			mountRouters.delete(bundle.name);
			delete extensions[bundle.name];
			loadedBundles.delete(bundle.name);
		}

		const loadExtension = Effect.fn("loadExtension")(function* (
			bundle: MoonCG.Bundle,
		) {
			try {
				mountExtension(bundle);
			} catch (err: unknown) {
				yield* bundleService.remove(bundle.name);
				log.warn(
					"Failed to mount %s extension:\n",
					bundle.name,
					stringifyError(err),
				);
				if (sentryEnabled) {
					(err as Error).message = `Failed to mount ${bundle.name} extension: ${
						(err as Error)?.message ?? err
					}`;
					Sentry.captureException(err);
				}
			}
		});

		// `all` returns a fresh copy, so mutating this array is safe.
		const allBundles = yield* bundleService.all();

		// Track which bundles we know are fully loaded (extension and all)
		const fullyLoaded: MoonCG.Bundle[] = [];

		while (allBundles.length > 0) {
			const startLen = allBundles.length;
			for (let i = 0; i < startLen; i++) {
				const bundle = allBundles[i];
				if (!bundle) {
					continue;
				}

				// If this bundle has no dependencies, load it and remove it from the list
				if (!bundle.bundleDependencies) {
					log.debug("Bundle %s has no dependencies", bundle.name);

					if (bundle.hasExtension) {
						yield* loadExtension(bundle);
					}

					fullyLoaded.push(bundle);
					allBundles.splice(i, 1);
					break;
				}

				// If this bundle has dependencies, and all of them are satisfied, load it and remove it from the list
				if (bundleDepsSatisfied(bundle, fullyLoaded)) {
					log.debug(
						"Bundle %s has extension with satisfied dependencies",
						bundle.name,
					);

					if (bundle.hasExtension) {
						yield* loadExtension(bundle);
					}

					fullyLoaded.push(bundle);
					allBundles.splice(i, 1);
					break;
				}
			}

			const endLen = allBundles.length;
			if (startLen === endLen) {
				// Any bundles left over must have had unsatisfied dependencies.
				// Print a warning about each bundle, and what its unsatisfied deps were.
				// Then, unload the bundle.
				for (const bundle of allBundles) {
					const unsatisfiedDeps = [];

					for (const dep in bundle.bundleDependencies) {
						if (!{}.hasOwnProperty.call(bundle.bundleDependencies, dep)) {
							continue;
						}

						const satisfied = satisfiedDepNames.get(bundle);
						if (satisfied?.includes(dep)) {
							continue;
						}

						unsatisfiedDeps.push(`${dep}@${bundle.bundleDependencies[dep]}`);
					}

					log.error(
						'Bundle "%s" can not be loaded, as it has unsatisfied dependencies:\n',
						bundle.name,
						unsatisfiedDeps.join(", "),
					);
					yield* bundleService.remove(bundle.name);
				}

				log.error(
					"%d bundle(s) can not be loaded because they have unsatisfied dependencies",
					endLen,
				);
				break;
			}
		}

		log.trace("Completed extension mounting");

		function emitToAllInstances<K extends keyof ExtensionEventMap>(
			eventName: K,
			...params: Parameters<ExtensionEventMap[K]>
		) {
			for (const instance of apiInstances) {
				instance.emit(eventName, ...params);
			}
		}

		function bundleDepsSatisfied(
			bundle: MoonCG.Bundle,
			loadedBundlesArr: MoonCG.Bundle[],
		): boolean {
			const deps = bundle.bundleDependencies;
			if (!deps) {
				return true;
			}

			const unsatisfiedDepNames = Object.keys(deps);
			const arr = satisfiedDepNames.get(bundle)?.slice(0) ?? [];

			loadedBundlesArr.forEach((loadedBundle) => {
				// Find out if this loaded bundle is one of the dependencies of the bundle in question.
				// If so, check if the version loaded satisfies the dependency.
				const index = unsatisfiedDepNames.indexOf(loadedBundle.name);
				if (index > -1) {
					if (
						semver.satisfies(loadedBundle.version, deps[loadedBundle.name]!)
					) {
						arr.push(loadedBundle.name);
						unsatisfiedDepNames.splice(index, 1);
					}
				}
			});

			satisfiedDepNames.set(bundle, arr);
			return unsatisfiedDepNames.length === 0;
		}

		/**
		 * Hot-reloads a bundle's extension at runtime.
		 *
		 * Reloads cascade topologically: all loaded extensions that
		 * (transitively) depend on the bundle are unloaded first, then the
		 * bundle itself; loading happens in reverse order. Replicant state
		 * survives the reload.
		 *
		 * A bundle whose extension fails to load stays running
		 * (graphics/dashboard keep working), but its extension remains
		 * unloaded until the next successful change.
		 */
		const reloadExtension = Effect.fn("reloadExtension")(function* (
			bundleName: string,
		) {
			if (!config.hotReload.extensions) {
				return;
			}

			const bundle = yield* bundleService.find(bundleName);
			if (!bundle?.hasExtension) {
				return;
			}

			// Collect the affected bundles in unload order: the (transitive)
			// dependents come first (deepest dependents at the front), the
			// target bundle itself comes last.
			const unloadOrder: MoonCG.Bundle[] = [];
			const visited = new Set<string>();
			const visit = (name: string, visitedBundle: MoonCG.Bundle) => {
				if (visited.has(name)) {
					return;
				}

				visited.add(name);
				for (const [dependentName, dependentBundle] of loadedBundles) {
					if (dependentName === name) {
						continue;
					}

					if (
						dependentBundle.bundleDependencies &&
						{}.hasOwnProperty.call(dependentBundle.bundleDependencies, name)
					) {
						visit(dependentName, dependentBundle);
					}
				}

				unloadOrder.push(visitedBundle);
			};
			visit(bundle.name, bundle);

			log.info(
				"Change detected in %s, reloading extension(s): %s",
				bundle.name,
				unloadOrder.map((affected) => affected.name).join(", "),
			);

			// 1. Unload every affected extension (dependents first).
			yield* Effect.sync(() => {
				for (const affected of unloadOrder) {
					unloadExtension(affected);
				}
			});

			// 2. Purge the require cache of every affected bundle directory,
			// so the next require re-reads the code from disk. (Note: this
			// only works for CommonJS extensions; ESM extensions cannot be
			// hot-reloaded.)
			yield* Effect.sync(() => {
				for (const affected of unloadOrder) {
					purgeModuleCache(affected.dir);
				}
			});

			// 3. Load everything back in reverse (dependency) order.
			const reloadedNames: string[] = [];
			for (const affected of [...unloadOrder].reverse()) {
				yield* Effect.try({
					try: () => {
						mountExtension(affected);
					},
					catch: (error) =>
						error instanceof Error ? error : new Error(String(error)),
				}).pipe(
					Effect.matchEffect({
						onSuccess: () =>
							Effect.sync(() => {
								reloadedNames.push(affected.name);
								log.info("Reloaded %s extension", affected.name);
							}),
						onFailure: (error) =>
							Effect.sync(() => {
								log.warn(
									"Failed to reload %s extension, it will remain unloaded until the next successful change:\n",
									affected.name,
									stringifyError(error),
								);
							}).pipe(
								Effect.andThen(
									PubSub.publish(
										bundleService.subscribe,
										BundleEvent.InvalidBundle({ bundle: affected, error }),
									),
								),
							),
					}),
				);
			}

			// `extensionsLoaded` deliberately keeps its "all extensions were
			// loaded at startup" semantics and is NOT re-emitted here.
			// Dependents can react to `extensionReloaded` instead.
			for (const reloadedName of reloadedNames) {
				emitToAllInstances("extensionReloaded", reloadedName);
			}
		});

		return {
			emitToAllInstances,
			getExtensions: () => ({ ...extensions }),
			reloadExtension,
		};
	},
);
